### ISSUE TITLE
Switch not working on Philips 55OLED803

### ISSUE THREAD

**Issue by FireHelmet** [Mr-Groch/ambihue#1]
Hello @Mr-Groch 

I followed your instructions, the switch appears in HA and his default state is ON but I'm not able to control the ambilight state.
Even if I use the switch in ON or OFF my TV doesn't respond. I used the credentials already generated when I tried to use another Ambilight integration.

My HA setup is based on HA Core 2021.11.3
My TV, a Philips 55OLED803 on Android 8

Could you help me?

Thank you for your support and your work !

**Comment by Mr-Groch** [comment]
Please paste your configuration and logs (from initialization and when you're trying to switch the switch)

**Comment by FireHelmet** [comment]
@Mr-Groch , I will do it tomorrow.
Also, should I set a specific log level ? Only from HA ? If not, could you give me the how to ?

Thank you !

**Comment by FireHelmet** [comment]
@Mr-Groch I was not able to get log about your custom component even when I enabled logs as DEBUG.

I used this article : https://www.home-assistant.io/integrations/logger/

Could you give me more info ? should I enable another log somewhere ?

Thank you for your support !

**Comment by Mr-Groch** [comment]
If there is nothing in logs, then it means that custom component is properly initialized and communication with TV is also succesfull when switching Ambilight + Hue... Are you sure that when you switch AmbiHue switch in HA, Ambilight + Hue option in TV is not activated? Maybe it is not properly configured in TV setup?

You can also try switch Ambilight+Hue option from TV, and observe if AmbiHue switch in HA changes state

**Comment by FireHelmet** [comment]
I'm sure yes,. I also re-paired the the TV by using new passcode (see attachment) and used username and password in secrets.yaml. I restarted HA and tested again, same result.

Tests :
Reboot HA > switch.ambilight [State] OFF
Power TV to ON with remote  > switch.ambilight [State] OFF
Ambilight to ON with remote > switch.ambilight [State] OFF
switch.ambilight OFF to ON (manually) > [State] Unavailable > [State] OFF
Ambilight to OFF with remote > switch.ambilight [State] OFF
switch.ambilight OFF to ON (manually) > [State] ON > Ambilight stay OFF but switch.ambilight stay ON

See my config in switch.yaml (The IP address is good) :
```yaml
- platform: philips_ambilight+hue
  name: Ambilight
  host: 192.168.1.246
  secured_transport: true
  api_version: 6
  username: !secret philips_ambilight_username
  password: !secret philips_ambilight_password
  scan_interval: 5
```
<img width="668" alt="pairing" src="https://user-images.githubusercontent.com/17533298/142681119-2e1ac8fe-9f86-4ae9-8fb4-58581f11b717.png">

We could have a live debug session if you are available. Just let me know your preferred date/time + timezone and the remote tool (Teamviewer, etc...)

Thank you for your support !

**Comment by Mr-Groch** [comment]
You are mentioning just Ambilight, not Ambilight + Hue. This switch component controls Ambilight + Hue feature of Philips TV to sync TVs Ambilight with Philips Hue bridge:

https://www.youtube.com/watch?v=tM1_afqeqFM

**Comment by FireHelmet** [comment]
Oh okay, apologies ! I tried this script [here](https://github.com/eslavnov/pylips) and used as a "[Command line Switch](https://www.home-assistant.io/integrations/switch.command_line/)" in HA it works perfectly!

Thank you for your quick answer and support !
