### ISSUE TITLE
New Entity after host restarts

### ISSUE THREAD

**Issue by oekinger** [Mr-Groch/ambihue#2]
Good Morning,
with v 0.0.7 I have a strange issue:
every time I restart my host, I got a new entity switch.ambilight_hue_2, switch.ambilight_hue_3 and so on; the "older" entitys have the state recovered and only the newest works.
[![CleanShot 2022-01-23 at 09 23 19](https://user-images.githubusercontent.com/43011000/150670459-f07f4a18-edd7-466a-a4a0-cbc17c812846.png)
](url)
Thanks,
Marko

**Comment by SebastiaanKlippert** [comment]
Thanks for opening this issue, I only wanted to confirm that I have the same problem.
I was looking for a fix but did not realize there were now two switches.
![afbeelding](https://user-images.githubusercontent.com/6223360/150816242-a5b5748a-607a-4213-b069-69e7eb3f6289.png)
I thought I had an issue with it not connecting to the TV anymore, but thanks to your issue report I see that only the second one is working now and is also displaying the availability history correctly.
Running Home Assistant 2021.12.10 and 0.0.7.

[edit] Maybe it helps somebody as a workaround or to debug: The new enities don't have a unique ID, for me it helped to remove the original entity (switch.ambilight_hue) and then restart HA, that created the first one again and removed the others. That is at least a temporary fix.

**Comment by oekinger** [comment]
> [edit] Maybe it helps somebody as a workaround or to debug: The new enities don't have a unique ID, for me it helped to remove the original entity (switch.ambilight_hue) and then restart HA, that created the first one again and removed the others. That is at least a temporary fix.

That helps for me too :-). Thank you for that hint.

Update: Helps only short time. After some Updates on hassio, sometimes it starts duplicatig, sometimes not.

**Comment by Rayhzvj** [comment]
same here.

**Comment by SebastiaanKlippert** [comment]
This seems to have been fixed in Homeassistant

**Comment by oekinger** [comment]
> This seems to have been fixed in Homeassistant

Not for me:

![grafik](https://user-images.githubusercontent.com/43011000/156913396-4a14fb3c-b3e6-44af-a8f4-25af2f3e369e.png)

**Comment by oekinger** [comment]
@Mr-Groch Pleas roll back to previous version; I better go without unique identity then with problems after some (not every) reboot ;-)

**Comment by Mr-Groch** [comment]
Hi, sorry for late answer... On your screenshot I can see 2 entities from 2 integrations - it looks that some other integration conflicts with ambilight+hue - what is "Schalter" integration?

EDIT: Please also paste here logs from Home Assistant initialization

**Comment by oekinger** [comment]
Hi,
no problem: I can use it eiher ;-).
My guess is, that one entity is generated by the integration? and another by the yaml config (I'm not deep into hassio nor in programming)

![grafik](https://user-images.githubusercontent.com/43011000/157836011-4e1765c3-17df-43b6-bbaa-199defecb64d.png)

The log doesn't show something for me

![grafik](https://user-images.githubusercontent.com/43011000/157837017-cca08c08-2545-4417-8223-fb83fdfad5e1.png)

**Comment by Mr-Groch** [comment]
After this restart ambilight+hue entity was doubled? There is no error or waring in log after 9:12:28 ?

Can you try remove (comment out) ambilight+hue from your configuration, restart HA, delete all entities from ambilight+hue, reenable in configuration and restart again?

**Comment by oekinger** [comment]
My fault: after I made the screenshot I manually deleteted one entity and renamed the other one. For me it is still unclear, when exactly it starts to produce duplicates, but the trigger is a host-restart.

After commentig out HUE+ in config.yaml the "Schalter" (german for switch) disappeared and acually I have no Ambulight+Hue entity at all. Also in the logs I only can find the warning (HACS), nothing else. Should I also remove the HACS-Integration itself?

**Comment by Mr-Groch** [comment]
No, leave HACS. If you don't have any ambilight+hue entity, reenable integration in config and restart HA. Observe if any errors or warnings appears in logs after restart. If all works fine - restart again and check again. If entity will be duplicated - it should be some warning or error in logs...

**Comment by oekinger** [comment]
Re-Enabled, restarted. Ambilight+Hue entity is back (once) but: without unique identity

![grafik](https://user-images.githubusercontent.com/43011000/157843107-cc6dd96f-a19f-4d72-a1a6-cb45ffa2b74a.png)
![grafik](https://user-images.githubusercontent.com/43011000/157843180-c9882365-ff73-487e-9138-8e9e225b4a93.png)
Log seems ok
![grafik](https://user-images.githubusercontent.com/43011000/157843306-a979f8fb-b0a0-4e77-91e3-5a10549f76b5.png)

**Comment by oekinger** [comment]
Restarted again: still only one entity, no change in logs. Might this problem only occur. when I resart host while TV is on (outherwise ambilight+Hue isn't available)? Try this out, mom pls

Does not change anything. Result at the moment:

- No duplicates after host restart but
- the working entity does not have a unique id

This looks interessant in the log

![grafik](https://user-images.githubusercontent.com/43011000/157848520-63de7f04-7fa5-4569-a9aa-ad7132c9dcd7.png)

I use a helper, but it's completely different 

![grafik](https://user-images.githubusercontent.com/43011000/157848792-bb0369a4-6310-47fc-899c-cd234ad7d26c.png)

**Comment by Mr-Groch** [comment]
I have an idea - this integration does not keep connection open with TV. It is trying to connect only on init and on update. If there is no connection on init - it will not have unique_id... But when TV is online on next init - it will get unique_id...

I think it should work well when you will delete all ambilight+hue entities, get TV online and restart HA - it should then be initialized properly

**Comment by oekinger** [comment]
> I have an idea - this integration does not keep connection open with TV. It is trying to connect only on init and on update. If there is no connection on init - it will not have unique_id... But when TV is online on next init - it will get unique_id...
> 
> I think it should work well when you will delete all ambilight+hue entities, get TV online and restart HA - it should then be initialized properly

I try this out :-)

**Comment by oekinger** [comment]
- TV is on
- Diaabled switch entity in yaml
- Restarted host
- Got the revovered entity WITH unique id (switch entity in yaml is still commented out completely) -> recovered switch does not work
![grafik](https://user-images.githubusercontent.com/43011000/157849800-48b434f9-7fd5-484e-afde-81c5c065878b.png)
- deleted that revocered entity, re-enabled switch in config.yaml and restarted another time
- and here we are: one (not) revovered entity with unique id that works 👍 

I'm not sure, if this will last but the workaround (turn tv on, disable switch in yaml, reboot, delete all ambi+ entitys, enable switch in yaml, restart) results in a working not revovered ambi+ entity with unique id.

**Comment by SebastiaanKlippert** [comment]
Hi @Mr-Groch thanks for looking into this.

I will also report back if this happens to me again. I found it remarkable that I had the exact same issue at the exact same time as @oekinger and it had always worked fine before. 
But I am also not sure why it is solved for me now, as far as  I know I only did some HASS upgrades but my TV is never on at that time.

**Comment by oekinger** [comment]
Hi @SebastiaanKlippert  and so far thanks @Mr-Groch (I love this function!),

I only can say the same: I updated hassio to the latest release (stable), even changed hardware (rpi4 -> x86 problem was there on rpi4 and also on x86), did restarts and updates with tv eiher on **and** off and that problem occurs sometimes. I guess its a mix of serveral trigeers that result in duplicating. 

A hint: the duplicates are always _restored_ and the working one is the last one (_2, _3 and so on)

**Comment by DibblesNL** [comment]
For what its worth i also am having this issue. Ive deleted 50 entities so far (at least). Its becoming a bit of a pain.

**Comment by Mr-Groch** [comment]
I will try to migrate this to new config flow (integration added from UI) - it should fix this, becouse I can hold uniqueid in config entry, what is not possible when configuration is in yaml... I'm checking for uniqueid from Philips TV and it should be available during init to work correctly

**Comment by Mr-Groch** [comment]
@DibblesNL @oekinger @SebastiaanKlippert @Rayhzvj I have reworked this integration to use UI Conflig Flow instead of `configuration.yaml`. Now unique_id of this entity will be saved in config entry after adding from UI and will be persistant.

Unfortunately the `+` sign in path and domain name caused trouble for Home Assistant when trying to add config entry to registry, so I have been forced to rename this integration. That causes HACS manager to unable to update this integration... You must remove and add it again using HACS....

**Comment by oekinger** [comment]
Good Morning @Mr-Groch , I just migrated to the new version that works fine and setup was very nice with only enter a PIN. Thank you so much for the new version 🥇 . I'll test it in the next days (with even some restarts :-).

**Comment by SebastiaanKlippert** [comment]
The new set-up is much better, thanks for the quick fix ❤️
